//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MundoMvc4.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MundoMvc4.Globalization.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capoeira.
        /// </summary>
        public static string Capoeira {
            get {
                return ResourceManager.GetString("Capoeira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string CapoeiraAbout {
            get {
                return ResourceManager.GetString("CapoeiraAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string CapoeiraHistory {
            get {
                return ResourceManager.GetString("CapoeiraHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        public static string CapoeiraMestres {
            get {
                return ResourceManager.GetString("CapoeiraMestres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mundo Capoera.
        /// </summary>
        public static string CapoeiraMundo {
            get {
                return ResourceManager.GetString("CapoeiraMundo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string CapoeiraMusic {
            get {
                return ResourceManager.GetString("CapoeiraMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School.
        /// </summary>
        public static string CapoeiraOurSchool {
            get {
                return ResourceManager.GetString("CapoeiraOurSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string Classes {
            get {
                return ResourceManager.GetString("Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Info.
        /// </summary>
        public static string ClassesAbout {
            get {
                return ResourceManager.GetString("ClassesAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string ClassesContacts {
            get {
                return ResourceManager.GetString("ClassesContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.A.Q..
        /// </summary>
        public static string ClassesFAQ {
            get {
                return ResourceManager.GetString("ClassesFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradations.
        /// </summary>
        public static string ClassesGradations {
            get {
                return ResourceManager.GetString("ClassesGradations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string ClassesSchedule {
            get {
                return ResourceManager.GetString("ClassesSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teachers.
        /// </summary>
        public static string ClassesTutors {
            get {
                return ResourceManager.GetString("ClassesTutors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string EventsArchive {
            get {
                return ResourceManager.GetString("EventsArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string EventsCalendar {
            get {
                return ResourceManager.GetString("EventsCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string EventsNews {
            get {
                return ResourceManager.GetString("EventsNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Region.
        /// </summary>
        public static string RegionMy {
            get {
                return ResourceManager.GetString("RegionMy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes Today.
        /// </summary>
        public static string RegionsClasses {
            get {
                return ResourceManager.GetString("RegionsClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For me.
        /// </summary>
        public static string RegionsForMe {
            get {
                return ResourceManager.GetString("RegionsForMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups and Gyms.
        /// </summary>
        public static string RegionsGroups {
            get {
                return ResourceManager.GetString("RegionsGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our News.
        /// </summary>
        public static string RegionsNews {
            get {
                return ResourceManager.GetString("RegionsNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other regions.
        /// </summary>
        public static string RegionsOther {
            get {
                return ResourceManager.GetString("RegionsOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string ResourcesArticles {
            get {
                return ResourceManager.GetString("ResourcesArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string ResourcesAudio {
            get {
                return ResourceManager.GetString("ResourcesAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary.
        /// </summary>
        public static string ResourcesDictionary {
            get {
                return ResourceManager.GetString("ResourcesDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string ResourcesPhoto {
            get {
                return ResourceManager.GetString("ResourcesPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs.
        /// </summary>
        public static string ResourcesSongs {
            get {
                return ResourceManager.GetString("ResourcesSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string ResourcesVideo {
            get {
                return ResourceManager.GetString("ResourcesVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show-Group.
        /// </summary>
        public static string ShowGroup {
            get {
                return ResourceManager.GetString("ShowGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string ShowGroupClasses {
            get {
                return ResourceManager.GetString("ShowGroupClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performances.
        /// </summary>
        public static string ShowGroupDances {
            get {
                return ResourceManager.GetString("ShowGroupDances", resourceCulture);
            }
        }
    }
}
