INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GActions','Create',1,'Create new',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GActions','Create',2,'Create new',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GActions','Create',3,'Create new',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GActions','Delete',1,'Delete',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GActions','Delete',2,'Delete',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GActions','Delete',3,'Delete',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GActions','Details',1,'Region',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GActions','Details',2,'Region',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GActions','Details',3,'Region',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GActions','Edit',1,'Edit',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GActions','Edit',2,'Edit',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GActions','Edit',3,'Edit',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GActions','EditLocal',1,'Localize',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GActions','EditLocal',2,'Localize',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GActions','EditLocal',3,'Localize',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GActions','Save',1,'Save',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GActions','Save',2,'Save',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GActions','Save',3,'Save',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GArticles','CreateLegend',1,'Specify values here',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GArticles','CreateLegend',2,'Specify values here',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GArticles','CreateLegend',3,'Specify values here',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GArticles','CreateTitle',1,'New Article',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GArticles','CreateTitle',2,'New Article',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GArticles','CreateTitle',3,'New Article',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GArticles','EditHeader',1,'Article Edit',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GArticles','EditHeader',2,'Article Edit',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GArticles','EditHeader',3,'Article Edit',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GArticles','EditLegend',1,'Edit It!',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GArticles','EditLegend',2,'Edit It!',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GArticles','EditLegend',3,'Edit It!',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GArticles','IndexTitle',1,'Edit It!',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GArticles','IndexTitle',2,'Edit It!',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GArticles','IndexTitle',3,'Edit It!',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GDelete','Title',1,'Delete',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GDelete','Title',2,'Delete',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GDelete','Title',3,'Delete',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GDelete','Submit',1,'Delete',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GDelete','Submit',2,'Delete',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GDelete','Submit',3,'Delete',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GDelete','Message',1,'Are you sure you want to delete {0}?',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GDelete','Message',2,'Are you sure you want to delete {0}?',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GDelete','Message',3,'Are you sure you want to delete {0}?',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GDelete','Head',1,'Attention!',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GDelete','Head',2,'Attention!',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GDelete','Head',3,'Attention!',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGroups','CreateTitle',1,'Create Group',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGroups','CreateTitle',2,'Create Group',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGroups','CreateTitle',3,'Create Group',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGroups','EtidTitle',1,'Edit Group',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGroups','EtidTitle',2,'Edit Group',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGroups','EtidTitle',3,'Edit Group',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGroups','Gyms',1,'Gyms',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGroups','Gyms',2,'Gyms',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGroups','Gyms',3,'Gyms',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGroups','GymsAdd',1,'Add Gym',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGroups','GymsAdd',2,'Add Gym',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGroups','GymsAdd',3,'Add Gym',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGroups','IndexTitle',1,'Groups',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGroups','IndexTitle',2,'Groups',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGroups','IndexTitle',3,'Groups',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGroups','Legend',1,'Fill it!',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGroups','Legend',2,'Fill it!',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGroups','Legend',3,'Fill it!',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGyms','CreateTitle',1,'Create Gym',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGyms','CreateTitle',2,'Create Gym',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGyms','CreateTitle',3,'Create Gym',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGyms','EditSchedule',1,'Edit schedule',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGyms','EditSchedule',2,'Edit schedule',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGyms','EditSchedule',3,'Edit schedule',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGyms','EditTitle',1,'Edit Gym',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGyms','EditTitle',2,'Edit Gym',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGyms','EditTitle',3,'Edit Gym',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGyms','IndexTitle',1,'Gyms',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGyms','IndexTitle',2,'Gyms',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGyms','IndexTitle',3,'Gyms',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGyms','Legend',1,'Fill it!',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGyms','Legend',2,'Fill it!',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGyms','Legend',3,'Fill it!',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGyms','Schedule',1,'Schedule',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGyms','Schedule',2,'Schedule',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GGyms','Schedule',3,'Schedule',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','LogOnButton',1,'Log On',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','LogOnButton',2,'Log On',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','LogOnButton',3,'Log On',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','LogOnError',1,'Login was unsuccessful. Please correct the errors and try again.',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','LogOnError',2,'Login was unsuccessful. Please correct the errors and try again.',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','LogOnError',3,'Login was unsuccessful. Please correct the errors and try again.',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','LogOnLegend',1,'Log On Form',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','LogOnLegend',2,'Log On Form',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','LogOnLegend',3,'Log On Form',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','LogOnRegister',1,'Register',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','LogOnRegister',2,'Register',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','LogOnRegister',3,'Register',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','LogOnRegisterMessage',1,'if you don`t have an account.',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','LogOnRegisterMessage',2,'if you don`t have an account.',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','LogOnRegisterMessage',3,'if you don`t have an account.',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','LogOnSubHeader',1,'Enter your username and password below.',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','LogOnSubHeader',2,'Enter your username and password below.',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','LogOnSubHeader',3,'Enter your username and password below.',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','LogOnTitle',1,'Log On',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','LogOnTitle',2,'Log On',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','LogOnTitle',3,'Log On',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','RegisterButton',1,'Register',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','RegisterButton',2,'Register',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','RegisterButton',3,'Register',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','RegisterError',1,'Account creation was unsuccessful. Please correct the errors and try again.',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','RegisterError',2,'Account creation was unsuccessful. Please correct the errors and try again.',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','RegisterError',3,'Account creation was unsuccessful. Please correct the errors and try again.',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','RegisterInfo',1,'Passwords are required to be a minimum of {0} characters in length.',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','RegisterInfo',2,'Passwords are required to be a minimum of {0} characters in length.',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','RegisterInfo',3,'Passwords are required to be a minimum of {0} characters in length.',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','RegisterLegend',1,'Registration Form',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','RegisterLegend',2,'Registration Form',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','RegisterLegend',3,'Registration Form',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','RegisterSubHeader',1,'Use the form below to create a new account.',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','RegisterSubHeader',2,'Use the form below to create a new account.',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','RegisterSubHeader',3,'Use the form below to create a new account.',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','RegisterTitle',1,'Register',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','RegisterTitle',2,'Register',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMembership','RegisterTitle',3,'Register',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMetadata','Body',1,'Body/Content',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMetadata','Body',2,'Body/Content',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMetadata','Body',3,'Body/Content',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMetadata','InvalidMail',1,'Invalid e-mail format {0}',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMetadata','InvalidMail',2,'Invalid e-mail format {0}',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMetadata','InvalidMail',3,'Invalid e-mail format {0}',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMetadata','InvalidPhone',1,'Invalid phone format {0}',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMetadata','InvalidPhone',2,'Invalid phone format {0}',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMetadata','InvalidPhone',3,'Invalid phone format {0}',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMetadata','InvalidStringLength',1,'Max Length {0}, Min - {1}',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMetadata','InvalidStringLength',2,'Max Length {0}, Min - {1}',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMetadata','InvalidStringLength',3,'Max Length {0}, Min - {1}',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMetadata','IsActive',1,'Active',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMetadata','IsActive',2,'Active',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMetadata','IsActive',3,'Active',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMetadata','Name',1,'Display Name',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMetadata','Name',2,'Display Name',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMetadata','Name',3,'Display Name',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMetadata','Required',1,'Required field',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMetadata','Required',2,'Required field',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMetadata','Required',3,'Required field',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMetadata','SysName',1,'System name',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMetadata','SysName',2,'System name',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GMetadata','SysName',3,'System name',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GNews','CreateTitle',1,'Create news item',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GNews','CreateTitle',2,'Create news item',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GNews','CreateTitle',3,'Create news item',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GNews','EditTitle',1,'Edit news',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GNews','EditTitle',2,'Edit news',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GNews','EditTitle',3,'Edit news',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GNews','IndexTitle',1,'News',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GNews','IndexTitle',2,'News',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GNews','IndexTitle',3,'News',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GNews','Legend',1,'Fill news',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GNews','Legend',2,'Fill news',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GNews','Legend',3,'Fill news',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','CreateLegend',1,'New region',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','CreateLegend',2,'New region',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','CreateLegend',3,'New region',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','CreateSubmit',1,'Create',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','CreateSubmit',2,'Create',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','CreateSubmit',3,'Create',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','CreateTitle',1,'Create new region',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','CreateTitle',2,'Create new region',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','CreateTitle',3,'Create new region',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','EMail',1,'E-Mail',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','EMail',2,'E-Mail',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','EMail',3,'E-Mail',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','EMailDescr',1,'E-Mail is displayed on main page',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','EMailDescr',2,'E-Mail is displayed on main page',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','EMailDescr',3,'E-Mail is displayed on main page',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','IndexTitle',1,'Our regions',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','IndexTitle',2,'Our regions',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','IndexTitle',3,'Our regions',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','LinkGroupCreate',1,'Create new group',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','LinkGroupCreate',2,'Create new group',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','LinkGroupCreate',3,'Create new group',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','LinkGroups',1,'Region groups',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','LinkGroups',2,'Region groups',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','LinkGroups',3,'Region groups',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','LinkNews',1,'Region news',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','LinkNews',2,'Region news',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','LinkNews',3,'Region news',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','Phone',1,'Contact phone',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','Phone',2,'Contact phone',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','Phone',3,'Contact phone',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','PhoneDescr',1,'Phone number displayed on main page',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','PhoneDescr',2,'Phone number displayed on main page',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GRegions','PhoneDescr',3,'Phone number displayed on main page',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GSchedule','Fr',1,'Fr',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GSchedule','Fr',2,'Fr',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GSchedule','Fr',3,'Fr',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GSchedule','Mo',1,'Mo',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GSchedule','Mo',2,'Mo',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GSchedule','Mo',3,'Mo',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GSchedule','Sa',1,'Sa',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GSchedule','Sa',2,'Sa',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GSchedule','Sa',3,'Sa',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GSchedule','Su',1,'Su',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GSchedule','Su',2,'Su',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GSchedule','Su',3,'Su',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GSchedule','Th',1,'Th',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GSchedule','Th',2,'Th',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GSchedule','Th',3,'Th',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GSchedule','Tu',1,'Tu',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GSchedule','Tu',2,'Tu',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GSchedule','Tu',3,'Tu',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GSchedule','We',1,'We',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GSchedule','We',2,'We',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GSchedule','We',3,'We',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GSections','EditTitle',1,'Edit section',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GSections','EditTitle',2,'Edit section',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GSections','EditTitle',3,'Edit section',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GSections','Legend',1,'Section details',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GSections','Legend',2,'Section details',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('GSections','Legend',3,'Section details',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','HomeTitle',1,'Mundocapoeira Home',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','HomeTitle',2,'Mundocapoeira Home',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','HomeTitle',3,'Mundocapoeira Home',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','LinkCopyright',1,'Mundocapoeira development',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','LinkCopyright',2,'Mundocapoeira development',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','LinkCopyright',3,'Mundocapoeira development',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','LinkFacebook',1,'Facebook',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','LinkFacebook',2,'Facebook',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','LinkFacebook',3,'Facebook',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','LinkLogOff',1,'Log off',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','LinkLogOff',2,'Log off',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','LinkLogOff',3,'Log off',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','LinkLogOn',1,'Log on',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','LinkLogOn',2,'Log on',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','LinkLogOn',3,'Log on',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','LinkNews',1,'News',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','LinkNews',2,'News',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','LinkNews',3,'News',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','LinkRegister',1,'Register',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','LinkRegister',2,'Register',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','LinkRegister',3,'Register',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','LinkTwitter',1,'Twitter',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','LinkTwitter',2,'Twitter',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','LinkTwitter',3,'Twitter',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','LinkVKontakte',1,'vKontakte',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','LinkVKontakte',2,'vKontakte',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','LinkVKontakte',3,'vKontakte',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','TitleRegionSelect',1,'Select region',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','TitleRegionSelect',2,'Select region',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Master','TitleRegionSelect',3,'Select region',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','Capoeira',1,'Capoeira',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','Capoeira',2,'Capoeira',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','Capoeira',3,'Capoeira',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','CapoeiraAbout',1,'About',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','CapoeiraAbout',2,'About',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','CapoeiraAbout',3,'About',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','CapoeiraHistory',1,'History',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','CapoeiraHistory',2,'History',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','CapoeiraHistory',3,'History',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','CapoeiraMestres',1,'Master',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','CapoeiraMestres',2,'Master',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','CapoeiraMestres',3,'Master',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','CapoeiraMundo',1,'Mundo',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','CapoeiraMundo',2,'Mundo',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','CapoeiraMundo',3,'Mundo',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','CapoeiraMusic',1,'Music',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','CapoeiraMusic',2,'Music',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','CapoeiraMusic',3,'Music',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','CapoeiraOurSchool',1,'Our School',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','CapoeiraOurSchool',2,'Our School',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','CapoeiraOurSchool',3,'Our School',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','Classes',1,'Classes',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','Classes',2,'Classes',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','Classes',3,'Classes',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ClassesAbout',1,'About',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ClassesAbout',2,'About',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ClassesAbout',3,'About',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ClassesContacts',1,'Contacts',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ClassesContacts',2,'Contacts',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ClassesContacts',3,'Contacts',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ClassesFAQ',1,'F.A.Q.',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ClassesFAQ',2,'F.A.Q.',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ClassesFAQ',3,'F.A.Q.',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ClassesGradations',1,'Gradations',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ClassesGradations',2,'Gradations',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ClassesGradations',3,'Gradations',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ClassesSchedule',1,'Scedule',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ClassesSchedule',2,'Scedule',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ClassesSchedule',3,'Scedule',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ClassesTutors',1,'Instructors',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ClassesTutors',2,'Instructors',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ClassesTutors',3,'Instructors',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','Events',1,'Events',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','Events',2,'Events',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','Events',3,'Events',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','EventsArchive',1,'Archive',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','EventsArchive',2,'Archive',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','EventsArchive',3,'Archive',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','EventsCalendar',1,'Calendar',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','EventsCalendar',2,'Calendar',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','EventsCalendar',3,'Calendar',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','EventsNews',1,'News',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','EventsNews',2,'News',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','EventsNews',3,'News',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','RegionMy',1,'My Region',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','RegionMy',2,'My Region',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','RegionMy',3,'My Region',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','RegionsClasses',1,'Classes',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','RegionsClasses',2,'Classes',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','RegionsClasses',3,'Classes',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','RegionsForMe',1,'For me',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','RegionsForMe',2,'For me',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','RegionsForMe',3,'For me',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','RegionsGroups',1,'Groups',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','RegionsGroups',2,'Groups',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','RegionsGroups',3,'Groups',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','RegionsNews',1,'News',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','RegionsNews',2,'News',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','RegionsNews',3,'News',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','RegionsOther',1,'Other',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','RegionsOther',2,'Other',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','RegionsOther',3,'Other',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','Resources',1,'Resources',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','Resources',2,'Resources',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','Resources',3,'Resources',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ResourcesArticles',1,'Articles',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ResourcesArticles',2,'Articles',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ResourcesArticles',3,'Articles',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ResourcesAudio',1,'Audio',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ResourcesAudio',2,'Audio',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ResourcesAudio',3,'Audio',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ResourcesDictionary',1,'Dictionary',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ResourcesDictionary',2,'Dictionary',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ResourcesDictionary',3,'Dictionary',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ResourcesPhoto',1,'Photos',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ResourcesPhoto',2,'Photos',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ResourcesPhoto',3,'Photos',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ResourcesSongs',1,'Songs',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ResourcesSongs',2,'Songs',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ResourcesSongs',3,'Songs',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ResourcesVideo',1,'Video',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ResourcesVideo',2,'Video',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ResourcesVideo',3,'Video',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ShowGroup',1,'Show Group',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ShowGroup',2,'Show Group',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ShowGroup',3,'Show Group',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ShowGroupClasses',1,'Classes',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ShowGroupClasses',2,'Classes',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ShowGroupClasses',3,'Classes',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ShowGroupDances',1,'Dances',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ShowGroupDances',2,'Dances',1)
INSERT INTO [dbo].[Resources] ([TypeName],[Property],[LangId],[Value],[IsSystem]) VALUES ('Menu','ShowGroupDances',3,'Dances',1)
